### ISSUE TITLE
*Collection types return empty methods

### ISSUE THREAD

**Issue by asklar** [MikeHillberg/middleweight-reflection#9]
```csharp
// get a MrType of WUX.Media.Animation.TransitionCollection
var t = LoadContext.GetType("Windows.UI.Xaml.Media.Animation.TransitionCollection");
t.GetMethodsAndConstructors(out var methods, out var ctors);

var insertAt = methods.First(m => m.GetName() == "InsertAt");   
```

This throws, the methods array is empty

**Comment by asklar** [comment]
the methods are on `IList<T>` and `IEnumerable<T>` though

**Comment by MikeHillberg** [comment]
In the special projection of WinRT (`useWinRTProjections=true` in the constructor of `MrLoadContext`), `IVector<T>` is projected by System.Reflection.Metadata as an _explicit_ `IList<T>` interface implementation. Explicit interface implementations are implemented by .Net in metadata using a naming convention that WinRT doesn't know how to use.

But with `useWinRTProjections` off, `IVector<T>` doesn't get any special treatment, so it projects as `IVector<T>`, and its members show up as members of the class, which is the case for _implicit_ interface implementations in .Net-generated metadata, and all interface implementations in WinRT-generated metadata.
